# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "8a68647e834ce2d7a7bfcf081631f43a"
application_url = "https://react-router-app-1.netlify.app/"
embedded = false
name = "react-router-app"
handle = "react-router-app"

[webhooks]
api_version = "2024-10"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_orders"

[auth]
redirect_urls = [ "https://react-router-app-1.netlify.app/auth/callback" ]

[pos]
embedded = false

[build]
include_config_on_deploy = true
dev_store_url = "preview-store-a.myshopify.com" 